# Generated by Django 6.0.6 on 2026-06-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritealgorithm',
            options={'ordering': ['-created_at'], 'verbose_name': 'Favorite algorithm', 'verbose_name_plural': 'Favorite algorithms'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='recentlyviewedalgorithm',
            options={'ordering': ['-last_viewed_at'], 'verbose_name': 'Recently viewed algorithm', 'verbose_name_plural': 'Recently viewed algorithms'},
        ),
        migrations.AlterField(
            model_name='favoritealgorithm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='academic_interest',
            field=models.CharField(blank=True, max_length=255, verbose_name='Academic interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, max_length=255, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='recentlyviewedalgorithm',
            name='last_viewed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last viewed at'),
        ),
    ]
