# Generated by Django 6.0.6 on 2026-06-03 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('algorithms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('book', 'Book'), ('article', 'Article'), ('research_paper', 'Research Paper'), ('video', 'Video'), ('documentation', 'Documentation'), ('dataset', 'Dataset')], max_length=32)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('external_url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/files/')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='algorithms.algorithm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type'], name='resources_r_resourc_1a6f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['-created_at'], name='resources_r_created_83a7af_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['title'], name='resources_r_title_25cf8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourcebookmark',
            constraint=models.UniqueConstraint(fields=('user', 'resource'), name='unique_resource_bookmark_per_user'),
        ),
    ]
