# Generated by Django 6.0.6 on 2026-06-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-created_at'], 'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterModelOptions(
            name='resourcebookmark',
            options={'ordering': ['-created_at'], 'verbose_name': 'Resource bookmark', 'verbose_name_plural': 'Resource bookmarks'},
        ),
        migrations.AddField(
            model_name='resource',
            name='author_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author (Uzbek)'),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Description (Uzbek)'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Uzbek)'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Download count'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='External URL'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/files/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('book', 'Book'), ('article', 'Article'), ('research_paper', 'Research Paper'), ('video', 'Video'), ('documentation', 'Documentation'), ('dataset', 'Dataset')], max_length=32, verbose_name='Resource type'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='resourcebookmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
