"""Jazzmin admin theme configuration for ML Resource Hub."""

from django.utils.translation import gettext_lazy as _

JAZZMIN_SETTINGS = {
    "site_title": "ML Resource Hub",
    "site_header": "ML Resource Hub",
    "site_brand": "ML Resource Hub",
    "site_logo": None,
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": _("Welcome to ML Resource Hub admin"),
    "copyright": "ML Resource Hub",
    # Single search keeps the top bar clean and readable.
    "search_model": ["algorithms.Algorithm"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": _("Home"), "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": _("Website"), "url": "/", "new_window": True},
        {"name": _("Dashboard"), "url": "dashboard:dashboard", "new_window": True},
    ],
    "usermenu_links": [
        {"name": _("Website"), "url": "/", "new_window": True},
        {"model": "auth.user"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "accounts",
        "algorithms",
        "resources",
        "auth",
    ],
    "custom_links": {},
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "accounts": "fas fa-id-card",
        "accounts.profile": "fas fa-address-card",
        "accounts.favoritealgorithm": "fas fa-heart",
        "accounts.recentlyviewedalgorithm": "fas fa-history",
        "algorithms": "fas fa-brain",
        "algorithms.algorithm": "fas fa-project-diagram",
        "algorithms.comment": "fas fa-comments",
        "algorithms.rating": "fas fa-star",
        "resources": "fas fa-book-open",
        "resources.resource": "fas fa-file-alt",
        "resources.resourcebookmark": "fas fa-bookmark",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": "css/jazzmin-theme.css",
    "custom_js": "js/jazzmin-dark.js",
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    "language_chooser": True,
}

# SOSbot-style dark admin (Jazzmin 3 / AdminLTE 4).
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-danger",
    "default_theme_mode": "dark",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "default",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-outline-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
