# Generated by Django 6.0.6 on 2026-06-03 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithm',
            options={'ordering': ['name'], 'verbose_name': 'Algorithm', 'verbose_name_plural': 'Algorithms'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AddField(
            model_name='algorithm',
            name='advantages_uz',
            field=models.TextField(blank=True, verbose_name='Advantages (Uzbek)'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='algorithm_type_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Algorithm type (Uzbek)'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='applications_uz',
            field=models.TextField(blank=True, verbose_name='Applications (Uzbek)'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='complexity_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Complexity (Uzbek)'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Description (Uzbek)'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='disadvantages_uz',
            field=models.TextField(blank=True, verbose_name='Disadvantages (Uzbek)'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='mathematical_foundation_uz',
            field=models.TextField(blank=True, verbose_name='Mathematical foundation (Uzbek)'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='name_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (Uzbek)'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='advantages',
            field=models.TextField(verbose_name='Advantages'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='algorithm_type',
            field=models.CharField(max_length=255, verbose_name='Algorithm type'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='applications',
            field=models.TextField(verbose_name='Applications'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='category',
            field=models.CharField(choices=[('regression', 'Regression'), ('classification', 'Classification'), ('clustering', 'Clustering'), ('deep_learning', 'Deep Learning'), ('reinforcement_learning', 'Reinforcement Learning'), ('dimensionality_reduction', 'Dimensionality Reduction'), ('ensemble_learning', 'Ensemble Learning')], max_length=64, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='complexity',
            field=models.CharField(max_length=255, verbose_name='Complexity'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='disadvantages',
            field=models.TextField(verbose_name='Disadvantages'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='algorithms/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='mathematical_foundation',
            field=models.TextField(verbose_name='Mathematical foundation'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='View count'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
